[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-cv-ss = true
no-ligation = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"